# version: '3.5'
services:

  # region DBs

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=J92P1Y0j4T # This is temporary and will be managed differently in the future
    container_name: bns-db
    volumes:
      - bnsdata:/var/lib/postgresql/data
    ports:
      - "1401:1433"

  ar-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=J92P1Y0j4T # This is temporary and will be managed differently in the future
    container_name: ar-db
    volumes:
      - bnsdata:/var/lib/postgresql/data
    ports:
      - "1404:1433"
      
  auth-db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=J92P1Y0j4T # This is temporary and will be managed differently in the future
    container_name: auth-db
    volumes:
      - bnsdata:/var/lib/postgresql/data
    ports:
      - "1402:1433"

  pos-db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=J92P1Y0j4T # This is temporary and will be managed differently in the future
    container_name: pos-db
    volumes:
      - bnsdata:/var/lib/postgresql/data
    ports:
      - "1403:1433"

  # endregion

  bns-migration: 
    container_name: bns-migration
    depends_on:
      - db
    build: bns-api
    volumes:
      - ./src:/app/src
    command: >
      sh -c "npm install &&
             npx prisma db pull &&
             npx prisma generate && 
             npx prisma migrate dev &&
             npx prisma db seed"
  
  # region APIs

  bns-api:
    container_name: bns-api
    build:
      context: apis/bns-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links: 
      - db
    expose: 
      - "80"    

  ar-api: 
    container_name: ar-api
    build:
      context: apis/ar-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    links: 
      - db
    expose: 
       - "80"   

  pos-api: 
    container_name: pos-api
    build:
      context: apis/pos-api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    links: 
      - db
    expose: 
       - "80"   

  auth-api: 
    container_name: auth-api
    build:
      context: apis/auth-api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    links: 
      - db
    expose: 
       - "80"   

  # endregion

  bns-ui:
    container_name: bns-ui
    build: bns-ui
    ports:
      - "80:80"
    depends_on:
      - bns-api

  bns-mq:
    container_name: bns-mq
    image: rabbitmq:3
    restart: unless-stopped
  
volumes: 
  bnsdata:
    external: true