# version: '3.5'
services:
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=J92P1Y0j4T # This is temporary and will be managed differently in the future
    container_name: bns-db
    volumes:
      - bnsdata:/var/lib/postgresql/data
    ports:
      - "1401:1433"

  bns-migration: 
    container_name: bns-migration
    depends_on:
      - db
    build: bns-api
    volumes:
      - ./src:/app/src
    command: >
      sh -c "npm install &&
             npx prisma db pull &&
             npx prisma generate && 
             npx prisma migrate dev &&
             npx prisma db seed"
  
  bns-api:
    container_name: bns-api
    # env_file:
    #   - bns-api/.env.development
    build:
      context: bns-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links: 
      - db
    expose: 
      - "80"    

  bns-ui:
    container_name: bns-ui
    build: bns-ui
    ports:
      - "80:80"
    depends_on:
      - bns-api

volumes: 
  bnsdata:
    external: true