export enum Permission {
  APPLICATION_LOGIN = 0,
  INVENTORY = 1,
  INVENTORY_ADJUSTMENTS = 2,
  INVENTORY_COUNTS = 3,
  PRICING = 4,
  PROMOTIONS = 5,
  REPORTS = 6,
  REPORTS_INVENTORY = 7,
  REPORTS_PRICING = 8,
  REPORTS_PROMOTIONS = 9,
  SETTINGS = 10,
}
